### ISSUE TITLE
608px - 14% Difference

### ISSUE THREAD

**Issue by briannaneet** [briannaneet/content-page#1]
@muxlowc 

All of my other screenshots are passing through Markbot, except for the 608px size and there's only 14% difference. I'm not exactly sure what the difference is as it seems to be just that the text is shifted ever so slightly up or down. To my knowledge, I can't adjust the spacing that precisely, at least if I'm just using Typografier.

**Comment by muxlowc** [comment]
@briannaneet yah so many people had issues with getting it below 14%..

1) Add the same classes as below for your blockquote:
```
    <blockquote class="italic milli push-2">
      <p class="push-0">Believe green buds awaken in the spring,<br>That autumn paints the leaves with somber fire;<br>Believe I held my heart inviolate<br>To lavish on one man my hot desire.</p>
      <footer class="micro not-italic">— <cite class="not-italic">The Song of Bélit</cite></footer>
    </blockquote>
```

2) you need to add a footer to put your "…" like this:
  ```
  <footer class="push-2">…</footer>
    <hr class="pad-b-1-2">
```

Hopefully that helps!

**Comment by briannaneet** [comment]
@muxlowc thank you! I just had to change the classes for both the footer and cite in the blockquote and now it matches.
